package project1_polygonator;

import java.awt.Toolkit;
import javax.swing.*;

/**
 *
 * @author 980453413
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        this.getRootPane().setDefaultButton(CalculatejButton);

        this.setLocationRelativeTo(null);

        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/project1_polygonator/regularpolygon.gif"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        pnlInput = new javax.swing.JPanel();
        SidesjLabel = new javax.swing.JLabel();
        SidesjTextField = new javax.swing.JTextField();
        LengthjLabel = new javax.swing.JLabel();
        LengthjTextField = new javax.swing.JTextField();
        InnerAnglejLabel = new javax.swing.JLabel();
        AnglejTextField = new javax.swing.JTextField();
        CircumradiusjLabel = new javax.swing.JLabel();
        CircumradiusjTextField = new javax.swing.JTextField();
        ApothemjLabel = new javax.swing.JLabel();
        ApothemjTextField = new javax.swing.JTextField();
        PerimeterjLabel = new javax.swing.JLabel();
        PerimeterjTextField = new javax.swing.JTextField();
        DiagonalsjLabel = new javax.swing.JLabel();
        CentralAnglejTextField = new javax.swing.JTextField();
        CentralAnglejLabel = new javax.swing.JLabel();
        DiagonalsjTextField = new javax.swing.JTextField();
        ErrorjLabel = new javax.swing.JLabel();
        ErrorjTextField = new javax.swing.JTextField();
        CircleAreajTextField = new javax.swing.JTextField();
        CircleAreajLabel = new javax.swing.JLabel();
        CircleCircumferencejLabel = new javax.swing.JLabel();
        CircleCircumferencejTextField = new javax.swing.JTextField();
        AreajTextField = new javax.swing.JTextField();
        AreajLabel = new javax.swing.JLabel();
        jPanelButtons = new javax.swing.JPanel();
        CalculatejButton = new javax.swing.JButton();
        ClearjButton = new javax.swing.JButton();
        PrintjButton = new javax.swing.JButton();
        QuitjButton = new javax.swing.JButton();
        mnuBar = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        ClearjMenuItem = new javax.swing.JMenuItem();
        PrintjMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        QuitjMenuItem = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        AboutjMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setBorder(new javax.swing.border.MatteBorder(null));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Polygoninator/regularpolygon.gif"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Book Antiqua", 0, 36)); // NOI18N
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1_polygonator/regularpolygon.gif"))); // NOI18N
        lblTitle.setText("Regular Polygons");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlInput.setBorder(new javax.swing.border.MatteBorder(null));

        SidesjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SidesjLabel.setText("Number of Sides:");

        LengthjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LengthjLabel.setText("Side Length:");

        InnerAnglejLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        InnerAnglejLabel.setText("Interior Angle:");

        CircumradiusjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CircumradiusjLabel.setText("Circumradius:");

        ApothemjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ApothemjLabel.setText("Apothem:");

        PerimeterjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PerimeterjLabel.setText("Perimeter of Polygon:");

        DiagonalsjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DiagonalsjLabel.setText("Number of Distinct Diagonals:");

        CentralAnglejLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CentralAnglejLabel.setText("Central Angle:");

        ErrorjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ErrorjLabel.setText("% Error in Perimeter:");

        CircleAreajLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CircleAreajLabel.setText("Area of Circumcircle:");

        CircleCircumferencejLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CircleCircumferencejLabel.setText("Circumference of Circumcircle:");

        AreajLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AreajLabel.setText("Area of Polygon:");

        javax.swing.GroupLayout pnlInputLayout = new javax.swing.GroupLayout(pnlInput);
        pnlInput.setLayout(pnlInputLayout);
        pnlInputLayout.setHorizontalGroup(
            pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputLayout.createSequentialGroup()
                        .addComponent(SidesjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SidesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputLayout.createSequentialGroup()
                        .addComponent(LengthjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LengthjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputLayout.createSequentialGroup()
                        .addComponent(InnerAnglejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AnglejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputLayout.createSequentialGroup()
                        .addComponent(CircumradiusjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CircumradiusjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputLayout.createSequentialGroup()
                        .addComponent(ApothemjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ApothemjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputLayout.createSequentialGroup()
                        .addComponent(PerimeterjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PerimeterjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputLayout.createSequentialGroup()
                        .addComponent(AreajLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AreajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputLayout.createSequentialGroup()
                        .addComponent(CircleCircumferencejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CircleCircumferencejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputLayout.createSequentialGroup()
                        .addComponent(CircleAreajLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CircleAreajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputLayout.createSequentialGroup()
                        .addComponent(ErrorjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ErrorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputLayout.createSequentialGroup()
                        .addComponent(CentralAnglejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CentralAnglejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputLayout.createSequentialGroup()
                        .addComponent(DiagonalsjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DiagonalsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlInputLayout.setVerticalGroup(
            pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SidesjLabel)
                    .addComponent(SidesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LengthjLabel)
                    .addComponent(LengthjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InnerAnglejLabel)
                    .addComponent(AnglejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CircumradiusjLabel)
                    .addComponent(CircumradiusjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApothemjLabel)
                    .addComponent(ApothemjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PerimeterjLabel)
                    .addComponent(PerimeterjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AreajLabel)
                    .addComponent(AreajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CircleCircumferencejLabel)
                    .addComponent(CircleCircumferencejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CircleAreajLabel)
                    .addComponent(CircleAreajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ErrorjLabel)
                    .addComponent(ErrorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CentralAnglejLabel)
                    .addComponent(CentralAnglejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiagonalsjLabel)
                    .addComponent(DiagonalsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelButtons.setBorder(new javax.swing.border.MatteBorder(null));
        jPanelButtons.setLayout(new java.awt.GridLayout());

        CalculatejButton.setMnemonic('C');
        CalculatejButton.setText("Calculate");
        CalculatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatejButtonActionPerformed(evt);
            }
        });
        jPanelButtons.add(CalculatejButton);

        ClearjButton.setMnemonic('L');
        ClearjButton.setText("Clear");
        ClearjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearjButtonActionPerformed(evt);
            }
        });
        jPanelButtons.add(ClearjButton);

        PrintjButton.setMnemonic('P');
        PrintjButton.setText("Print");
        PrintjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintjButtonActionPerformed(evt);
            }
        });
        jPanelButtons.add(PrintjButton);

        QuitjButton.setMnemonic('Q');
        QuitjButton.setText("Quit");
        QuitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitjButtonActionPerformed(evt);
            }
        });
        jPanelButtons.add(QuitjButton);

        mnuFile.setMnemonic('F');
        mnuFile.setText("File");

        ClearjMenuItem.setMnemonic('L');
        ClearjMenuItem.setText("Clear");
        ClearjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearjMenuItemActionPerformed(evt);
            }
        });
        mnuFile.add(ClearjMenuItem);

        PrintjMenuItem.setMnemonic('P');
        PrintjMenuItem.setText("Print");
        PrintjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintjMenuItemActionPerformed(evt);
            }
        });
        mnuFile.add(PrintjMenuItem);
        mnuFile.add(jSeparator1);

        QuitjMenuItem.setMnemonic('Q');
        QuitjMenuItem.setText("Quit");
        QuitjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitjMenuItemActionPerformed(evt);
            }
        });
        mnuFile.add(QuitjMenuItem);

        mnuBar.add(mnuFile);

        mnuHelp.setMnemonic('H');
        mnuHelp.setText("Help");

        AboutjMenuItem.setMnemonic('A');
        AboutjMenuItem.setText("About");
        AboutjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutjMenuItemActionPerformed(evt);
            }
        });
        mnuHelp.add(AboutjMenuItem);

        mnuBar.add(mnuHelp);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int getInt(JTextField textbox) {
        int output = -1;
        try {
            output = Integer.parseInt(textbox.getText());
        } catch (NumberFormatException exp) {
            JOptionPane.showMessageDialog(null, "Illegal Input");
        }
        return output;
    }

    private double getDouble(JTextField textbox) {
        double output = -1;
        try {
            output = Double.parseDouble(textbox.getText());
        } catch (NumberFormatException exp) {
            JOptionPane.showMessageDialog(null, "Illegal Input");
        }
        return output;
    }
    private void CalculatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculatejButtonActionPerformed
        // Declare variables
        int sides;
        double length, innerAngle, circumradius, apothem, perimeter, area,
                circleCircumference, circleArea, errorPercent, centralAngle;

        // Set values
        sides = getInt(SidesjTextField);
        length = getDouble(LengthjTextField);

        // Additional validation
        // Run calculations
        innerAngle = (sides - 2) * (180.0 / sides);
        apothem = length
                / (2.0 * Math.tan(Math.PI / sides));
        circumradius = apothem / (Math.cos(Math.PI / sides));
        perimeter = sides * length;
        area = (1.0 / 2.0) * sides * apothem * sides;
        centralAngle = 360.0 / sides;
        circleCircumference = 2 * apothem * Math.PI;
        circleArea = Math.PI * (Math.pow(apothem, 2.0));
        errorPercent = 2 * (circleCircumference - perimeter) / circleCircumference;

        // Output results
        AnglejTextField.setText(String.valueOf(innerAngle));
        ApothemjTextField.setText(String.valueOf(apothem));
        AreajTextField.setText(String.valueOf(area));
        CentralAnglejTextField.setText(String.valueOf(centralAngle));
        CircleAreajTextField.setText(String.valueOf(circleArea));
        ErrorjTextField.setText(String.valueOf(errorPercent) + "%");

    }//GEN-LAST:event_CalculatejButtonActionPerformed

    private void ClearjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearjButtonActionPerformed

    private void PrintjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintjButtonActionPerformed

    private void QuitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuitjButtonActionPerformed

    private void ClearjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearjMenuItemActionPerformed
        ClearjButton.doClick();
    }//GEN-LAST:event_ClearjMenuItemActionPerformed

    private void PrintjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintjMenuItemActionPerformed
        PrintjButton.doClick();
    }//GEN-LAST:event_PrintjMenuItemActionPerformed

    private void QuitjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitjMenuItemActionPerformed
        QuitjButton.doClick();
    }//GEN-LAST:event_QuitjMenuItemActionPerformed

    private void AboutjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutjMenuItemActionPerformed
        AboutPolygonator about = new AboutPolygonator();
        about.setVisible(true);
    }//GEN-LAST:event_AboutjMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutjMenuItem;
    private javax.swing.JTextField AnglejTextField;
    private javax.swing.JLabel ApothemjLabel;
    private javax.swing.JTextField ApothemjTextField;
    private javax.swing.JLabel AreajLabel;
    private javax.swing.JTextField AreajTextField;
    private javax.swing.JButton CalculatejButton;
    private javax.swing.JLabel CentralAnglejLabel;
    private javax.swing.JTextField CentralAnglejTextField;
    private javax.swing.JLabel CircleAreajLabel;
    private javax.swing.JTextField CircleAreajTextField;
    private javax.swing.JLabel CircleCircumferencejLabel;
    private javax.swing.JTextField CircleCircumferencejTextField;
    private javax.swing.JLabel CircumradiusjLabel;
    private javax.swing.JTextField CircumradiusjTextField;
    private javax.swing.JButton ClearjButton;
    private javax.swing.JMenuItem ClearjMenuItem;
    private javax.swing.JLabel DiagonalsjLabel;
    private javax.swing.JTextField DiagonalsjTextField;
    private javax.swing.JLabel ErrorjLabel;
    private javax.swing.JTextField ErrorjTextField;
    private javax.swing.JLabel InnerAnglejLabel;
    private javax.swing.JLabel LengthjLabel;
    private javax.swing.JTextField LengthjTextField;
    private javax.swing.JLabel PerimeterjLabel;
    private javax.swing.JTextField PerimeterjTextField;
    private javax.swing.JButton PrintjButton;
    private javax.swing.JMenuItem PrintjMenuItem;
    private javax.swing.JButton QuitjButton;
    private javax.swing.JMenuItem QuitjMenuItem;
    private javax.swing.JLabel SidesjLabel;
    private javax.swing.JTextField SidesjTextField;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlInput;
    // End of variables declaration//GEN-END:variables
}
