package Movie;

import java.io.File;
import java.sql.Time;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Hiromi Cota
 */
public class MovieGUI extends javax.swing.JFrame {

    File films = new File("/src/Movie/Films.xml");
    File tickets = new File("/src/Movie/Ticket.xml");

    public final String[] regularTicket = {"Regular","Matinee"};
    
    /**
     * Creates new form MovieGUI
     */
    public MovieGUI() {
        initComponents();
        Splash splash = new Splash(this, true);
        splash.setLocationRelativeTo(null);
        this.setLocationRelativeTo(null);
        splash.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerjTabbedPane = new javax.swing.JTabbedPane();
        ticketjPanel = new javax.swing.JPanel();
        ticketShowTimejScrollPane = new javax.swing.JScrollPane();
        ticketShowTimejList = new javax.swing.JList<>();
        ticketShowTimejLabel = new javax.swing.JLabel();
        cartjScrollPane = new javax.swing.JScrollPane();
        cartjTextArea = new javax.swing.JTextArea();
        cartjLabel = new javax.swing.JLabel();
        duejTextField = new javax.swing.JTextField();
        tenderedjTextField = new javax.swing.JTextField();
        duejLabel = new javax.swing.JLabel();
        tenderedjLabel = new javax.swing.JLabel();
        addTicketjPanel = new javax.swing.JPanel();
        addPaneljLabel = new javax.swing.JLabel();
        addjSpinner = new javax.swing.JSpinner();
        addRegularjButton = new javax.swing.JButton();
        addSeniorjButton = new javax.swing.JButton();
        addChildjButton = new javax.swing.JButton();
        removeTicketjPanel = new javax.swing.JPanel();
        removePaneljLabel = new javax.swing.JLabel();
        removejSpinner = new javax.swing.JSpinner();
        removeRegularjButton = new javax.swing.JButton();
        removeSeniorjButton = new javax.swing.JButton();
        removeChildjButton = new javax.swing.JButton();
        changejLabel = new javax.swing.JLabel();
        changejTextField = new javax.swing.JTextField();
        checkOutjPanel = new javax.swing.JPanel();
        payCashjButton = new javax.swing.JButton();
        payCreditjButton = new javax.swing.JButton();
        payCheckjButton = new javax.swing.JButton();
        payRewardjButton = new javax.swing.JButton();
        clearAlljButton = new javax.swing.JButton();
        filmjPanel = new javax.swing.JPanel();
        filmjScrollPane = new javax.swing.JScrollPane();
        filmjList = new javax.swing.JList<>();
        addFilmjButton = new javax.swing.JButton();
        editFilmjButton = new javax.swing.JButton();
        deleteFilmjButton = new javax.swing.JButton();
        saveFilmjButton = new javax.swing.JButton();
        loadFilmjButton = new javax.swing.JButton();
        editFilmjPanel = new javax.swing.JPanel();
        runTimejLabel = new javax.swing.JLabel();
        runTimejSpinner = new javax.swing.JSpinner();
        ratingjLabel = new javax.swing.JLabel();
        ratingjSpinner = new javax.swing.JSpinner();
        filmIDjLabel = new javax.swing.JLabel();
        FilmIDjTextField = new javax.swing.JTextField();
        titlejTextField = new javax.swing.JTextField();
        titlejLabel = new javax.swing.JLabel();
        showTimejPanel = new javax.swing.JPanel();
        showTitlejLabel = new javax.swing.JLabel();
        showTitlejComboBox = new javax.swing.JComboBox<>();
        showEditjPanel = new javax.swing.JPanel();
        ticketsjLabel = new javax.swing.JLabel();
        ticketsjSpinner = new javax.swing.JSpinner();
        timejLabel = new javax.swing.JLabel();
        hourjSpinner = new javax.swing.JSpinner();
        minutesjSpinner = new javax.swing.JSpinner();
        showIDjLabel = new javax.swing.JLabel();
        showFilmIDjTextField = new javax.swing.JTextField();
        showTimejScrollPane = new javax.swing.JScrollPane();
        showTimejList = new javax.swing.JList<>();
        addShowTimejButton = new javax.swing.JButton();
        editShowTimejButton = new javax.swing.JButton();
        saveShowTimejButton = new javax.swing.JButton();
        deleteShowTimejButton = new javax.swing.JButton();
        loadShowTimejButton = new javax.swing.JButton();
        transjPanel = new javax.swing.JPanel();
        transjScrollPane = new javax.swing.JScrollPane();
        transOutputjTextArea = new javax.swing.JTextArea();
        nextTransjButton = new javax.swing.JButton();
        prevTransjButton = new javax.swing.JButton();
        transjTextField = new javax.swing.JTextField();
        lastTransjButton = new javax.swing.JButton();
        firstTransjButton = new javax.swing.JButton();
        transTextjLabel = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        filejMenu = new javax.swing.JMenu();
        loadFilmjMenuItem = new javax.swing.JMenuItem();
        saveFilmjMenuItem = new javax.swing.JMenuItem();
        filmjSeparator = new javax.swing.JPopupMenu.Separator();
        loadShowTimejMenuItem = new javax.swing.JMenuItem();
        saveShowTimejMenuItem = new javax.swing.JMenuItem();
        showTimejSeparator = new javax.swing.JPopupMenu.Separator();
        loadTransactionjMenuItem = new javax.swing.JMenuItem();
        saveTransactionjMenuItem = new javax.swing.JMenuItem();
        transactionjSeparator = new javax.swing.JPopupMenu.Separator();
        quitjMenuItem = new javax.swing.JMenuItem();
        editjMenu = new javax.swing.JMenu();
        helpjMenu = new javax.swing.JMenu();
        aboutjMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        containerjTabbedPane.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ticketjPanel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ticketShowTimejList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ticketShowTimejScrollPane.setViewportView(ticketShowTimejList);

        ticketShowTimejLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ticketShowTimejLabel.setText("Today's Showtimes");

        cartjTextArea.setColumns(20);
        cartjTextArea.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        cartjTextArea.setRows(5);
        cartjScrollPane.setViewportView(cartjTextArea);

        cartjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cartjLabel.setText("Cart:");

        duejTextField.setEditable(false);
        duejTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        duejTextField.setEnabled(false);

        tenderedjTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        duejLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        duejLabel.setText("Due:");

        tenderedjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tenderedjLabel.setText("Tendered:");

        addTicketjPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addTicketjPanel.setLayout(new java.awt.GridLayout(1, 5));

        addPaneljLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addPaneljLabel.setText("Add:");
        addTicketjPanel.add(addPaneljLabel);

        addjSpinner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addTicketjPanel.add(addjSpinner);

        addRegularjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addRegularjButton.setText("Regular");
        addRegularjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRegularjButtonActionPerformed(evt);
            }
        });
        addTicketjPanel.add(addRegularjButton);

        addSeniorjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addSeniorjButton.setText("Senior");
        addSeniorjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSeniorjButtonActionPerformed(evt);
            }
        });
        addTicketjPanel.add(addSeniorjButton);

        addChildjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addChildjButton.setText("Child");
        addChildjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChildjButtonActionPerformed(evt);
            }
        });
        addTicketjPanel.add(addChildjButton);

        removeTicketjPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        removeTicketjPanel.setLayout(new java.awt.GridLayout(1, 5));

        removePaneljLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removePaneljLabel.setText("Remove:");
        removeTicketjPanel.add(removePaneljLabel);

        removejSpinner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeTicketjPanel.add(removejSpinner);

        removeRegularjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeRegularjButton.setText("Regular");
        removeRegularjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRegularjButtonActionPerformed(evt);
            }
        });
        removeTicketjPanel.add(removeRegularjButton);

        removeSeniorjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeSeniorjButton.setText("Senior");
        removeSeniorjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSeniorjButtonActionPerformed(evt);
            }
        });
        removeTicketjPanel.add(removeSeniorjButton);

        removeChildjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeChildjButton.setText("Child");
        removeChildjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeChildjButtonActionPerformed(evt);
            }
        });
        removeTicketjPanel.add(removeChildjButton);

        changejLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        changejLabel.setText("Change:");

        changejTextField.setEditable(false);
        changejTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        changejTextField.setEnabled(false);

        checkOutjPanel.setLayout(new java.awt.GridLayout(1, 0));

        payCashjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        payCashjButton.setText("Cash");
        checkOutjPanel.add(payCashjButton);

        payCreditjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        payCreditjButton.setText("Credit");
        checkOutjPanel.add(payCreditjButton);

        payCheckjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        payCheckjButton.setText("Check");
        checkOutjPanel.add(payCheckjButton);

        payRewardjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        payRewardjButton.setText("Rewards");
        checkOutjPanel.add(payRewardjButton);

        clearAlljButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clearAlljButton.setText("Clear All");
        checkOutjPanel.add(clearAlljButton);

        javax.swing.GroupLayout ticketjPanelLayout = new javax.swing.GroupLayout(ticketjPanel);
        ticketjPanel.setLayout(ticketjPanelLayout);
        ticketjPanelLayout.setHorizontalGroup(
            ticketjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ticketjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ticketjPanelLayout.createSequentialGroup()
                        .addComponent(ticketShowTimejLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ticketjPanelLayout.createSequentialGroup()
                        .addComponent(ticketShowTimejScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(ticketjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ticketjPanelLayout.createSequentialGroup()
                                .addGroup(ticketjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ticketjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(addTicketjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(removeTicketjPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cartjScrollPane, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(cartjLabel))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(ticketjPanelLayout.createSequentialGroup()
                                .addGroup(ticketjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ticketjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(ticketjPanelLayout.createSequentialGroup()
                                            .addComponent(changejLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(changejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(ticketjPanelLayout.createSequentialGroup()
                                            .addGroup(ticketjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tenderedjLabel)
                                                .addComponent(duejLabel))
                                            .addGap(40, 40, 40)
                                            .addGroup(ticketjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(ticketjPanelLayout.createSequentialGroup()
                                                    .addGap(0, 0, Short.MAX_VALUE)
                                                    .addComponent(duejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(tenderedjTextField))))
                                    .addComponent(checkOutjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        ticketjPanelLayout.setVerticalGroup(
            ticketjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketjPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(ticketjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addTicketjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticketShowTimejLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ticketjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ticketShowTimejScrollPane)
                    .addGroup(ticketjPanelLayout.createSequentialGroup()
                        .addComponent(removeTicketjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cartjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cartjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ticketjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(duejLabel)
                            .addComponent(duejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ticketjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tenderedjLabel)
                            .addComponent(tenderedjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ticketjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(changejLabel)
                            .addComponent(changejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkOutjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        containerjTabbedPane.addTab("Sell Tickets", ticketjPanel);

        filmjList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        filmjList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        filmjList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        filmjScrollPane.setViewportView(filmjList);

        addFilmjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addFilmjButton.setText("Add New Film");

        editFilmjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editFilmjButton.setText("Edit Film");

        deleteFilmjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteFilmjButton.setText("Delete Film");

        saveFilmjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveFilmjButton.setText("Save Schedule");

        loadFilmjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loadFilmjButton.setText("Load Schedule");

        editFilmjPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        runTimejLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        runTimejLabel.setText("Run time:");

        runTimejSpinner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ratingjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ratingjLabel.setText("MPAA Rating:");

        ratingjSpinner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        filmIDjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        filmIDjLabel.setText("Film ID:");

        FilmIDjTextField.setEditable(false);
        FilmIDjTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FilmIDjTextField.setEnabled(false);

        titlejTextField.setEditable(false);
        titlejTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titlejTextField.setEnabled(false);

        titlejLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titlejLabel.setText("Title:");

        javax.swing.GroupLayout editFilmjPanelLayout = new javax.swing.GroupLayout(editFilmjPanel);
        editFilmjPanel.setLayout(editFilmjPanelLayout);
        editFilmjPanelLayout.setHorizontalGroup(
            editFilmjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editFilmjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editFilmjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editFilmjPanelLayout.createSequentialGroup()
                        .addComponent(filmIDjLabel)
                        .addGap(18, 18, 18)
                        .addComponent(FilmIDjTextField))
                    .addComponent(titlejTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editFilmjPanelLayout.createSequentialGroup()
                        .addComponent(ratingjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(ratingjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editFilmjPanelLayout.createSequentialGroup()
                        .addComponent(titlejLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(editFilmjPanelLayout.createSequentialGroup()
                        .addComponent(runTimejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(runTimejSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        editFilmjPanelLayout.setVerticalGroup(
            editFilmjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editFilmjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editFilmjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filmIDjLabel)
                    .addComponent(FilmIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(titlejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titlejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(editFilmjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ratingjLabel)
                    .addComponent(ratingjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(editFilmjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runTimejLabel)
                    .addComponent(runTimejSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout filmjPanelLayout = new javax.swing.GroupLayout(filmjPanel);
        filmjPanel.setLayout(filmjPanelLayout);
        filmjPanelLayout.setHorizontalGroup(
            filmjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filmjPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(filmjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filmjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(saveFilmjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadFilmjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteFilmjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addFilmjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editFilmjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(editFilmjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        filmjPanelLayout.setVerticalGroup(
            filmjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filmjPanelLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(filmjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filmjPanelLayout.createSequentialGroup()
                        .addComponent(addFilmjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editFilmjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteFilmjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveFilmjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loadFilmjButton))
                    .addComponent(filmjScrollPane)
                    .addComponent(editFilmjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(82, 82, 82))
        );

        containerjTabbedPane.addTab("Edit Films", filmjPanel);

        showTitlejLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        showTitlejLabel.setText("Editing Showtimes for:");

        showTitlejComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        showTitlejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        showEditjPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ticketsjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ticketsjLabel.setText("Available Tickets:");

        ticketsjSpinner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        timejLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        timejLabel.setText("Showing at: ");

        hourjSpinner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        minutesjSpinner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        showIDjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        showIDjLabel.setText("Film ID:");

        showFilmIDjTextField.setEditable(false);
        showFilmIDjTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        showFilmIDjTextField.setEnabled(false);

        javax.swing.GroupLayout showEditjPanelLayout = new javax.swing.GroupLayout(showEditjPanel);
        showEditjPanel.setLayout(showEditjPanelLayout);
        showEditjPanelLayout.setHorizontalGroup(
            showEditjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showEditjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showEditjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(showEditjPanelLayout.createSequentialGroup()
                        .addComponent(showIDjLabel)
                        .addGap(18, 18, 18)
                        .addComponent(showFilmIDjTextField))
                    .addGroup(showEditjPanelLayout.createSequentialGroup()
                        .addGroup(showEditjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(showEditjPanelLayout.createSequentialGroup()
                                .addComponent(timejLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hourjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minutesjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(showEditjPanelLayout.createSequentialGroup()
                                .addComponent(ticketsjLabel)
                                .addGap(23, 23, 23)
                                .addComponent(ticketsjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        showEditjPanelLayout.setVerticalGroup(
            showEditjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showEditjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showEditjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showIDjLabel)
                    .addComponent(showFilmIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(showEditjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timejLabel)
                    .addGroup(showEditjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(minutesjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hourjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(showEditjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketsjLabel)
                    .addComponent(ticketsjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        showTimejList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        showTimejList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        showTimejList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        showTimejScrollPane.setViewportView(showTimejList);

        addShowTimejButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addShowTimejButton.setText("Add New Showtime");

        editShowTimejButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editShowTimejButton.setText("Edit Showtime");

        saveShowTimejButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveShowTimejButton.setText("Save Schedule");

        deleteShowTimejButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteShowTimejButton.setText("Delete Showtime");

        loadShowTimejButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loadShowTimejButton.setText("Load Schedule");

        javax.swing.GroupLayout showTimejPanelLayout = new javax.swing.GroupLayout(showTimejPanel);
        showTimejPanel.setLayout(showTimejPanelLayout);
        showTimejPanelLayout.setHorizontalGroup(
            showTimejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showTimejPanelLayout.createSequentialGroup()
                .addGroup(showTimejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(showTimejPanelLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(showTitlejLabel)
                        .addGap(18, 18, 18)
                        .addComponent(showTitlejComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(showTimejPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(showTimejScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(showTimejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(showTimejPanelLayout.createSequentialGroup()
                                .addComponent(deleteShowTimejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(showTimejPanelLayout.createSequentialGroup()
                                .addGroup(showTimejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showTimejPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(editShowTimejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10))
                                    .addGroup(showTimejPanelLayout.createSequentialGroup()
                                        .addGroup(showTimejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addShowTimejButton)
                                            .addComponent(loadShowTimejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(saveShowTimejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(showEditjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        showTimejPanelLayout.setVerticalGroup(
            showTimejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showTimejPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(showTimejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(showTitlejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showTitlejLabel))
                .addGap(41, 41, 41)
                .addGroup(showTimejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(showTimejPanelLayout.createSequentialGroup()
                        .addComponent(addShowTimejButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editShowTimejButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteShowTimejButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(saveShowTimejButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loadShowTimejButton))
                    .addComponent(showTimejScrollPane)
                    .addComponent(showEditjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(138, 138, 138))
        );

        containerjTabbedPane.addTab("Edit Showtimes", showTimejPanel);

        transOutputjTextArea.setColumns(20);
        transOutputjTextArea.setRows(5);
        transjScrollPane.setViewportView(transOutputjTextArea);

        nextTransjButton.setText("Next");

        prevTransjButton.setText("Prev");

        lastTransjButton.setText("Last");

        firstTransjButton.setText("First");

        transTextjLabel.setText("Now viewing Transaction#");

        javax.swing.GroupLayout transjPanelLayout = new javax.swing.GroupLayout(transjPanel);
        transjPanel.setLayout(transjPanelLayout);
        transjPanelLayout.setHorizontalGroup(
            transjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(transjScrollPane)
                    .addGroup(transjPanelLayout.createSequentialGroup()
                        .addComponent(firstTransjButton)
                        .addGap(18, 18, 18)
                        .addComponent(prevTransjButton)
                        .addGap(18, 18, 18)
                        .addComponent(transTextjLabel)
                        .addGap(18, 18, 18)
                        .addComponent(transjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nextTransjButton)
                        .addGap(18, 18, 18)
                        .addComponent(lastTransjButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transjPanelLayout.setVerticalGroup(
            transjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transjPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(transjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextTransjButton)
                    .addComponent(prevTransjButton)
                    .addComponent(transjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastTransjButton)
                    .addComponent(firstTransjButton)
                    .addComponent(transTextjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transjScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        containerjTabbedPane.addTab("Review Transactions", transjPanel);

        filejMenu.setText("File");
        filejMenu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        loadFilmjMenuItem.setText("Load Films");
        filejMenu.add(loadFilmjMenuItem);

        saveFilmjMenuItem.setText("Save Films");
        filejMenu.add(saveFilmjMenuItem);
        filejMenu.add(filmjSeparator);

        loadShowTimejMenuItem.setText("Load Showtimes");
        loadShowTimejMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadShowTimejMenuItemActionPerformed(evt);
            }
        });
        filejMenu.add(loadShowTimejMenuItem);

        saveShowTimejMenuItem.setText("Save Showtimes");
        filejMenu.add(saveShowTimejMenuItem);
        filejMenu.add(showTimejSeparator);

        loadTransactionjMenuItem.setText("Load Transactions");
        filejMenu.add(loadTransactionjMenuItem);

        saveTransactionjMenuItem.setText("Save Transactions");
        filejMenu.add(saveTransactionjMenuItem);
        filejMenu.add(transactionjSeparator);

        quitjMenuItem.setText("Quit");
        quitjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitjMenuItemActionPerformed(evt);
            }
        });
        filejMenu.add(quitjMenuItem);

        jMenuBar.add(filejMenu);

        editjMenu.setText("Edit");
        editjMenu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuBar.add(editjMenu);

        helpjMenu.setText("Help");

        aboutjMenuItem.setText("About");
        helpjMenu.add(aboutjMenuItem);

        jMenuBar.add(helpjMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(containerjTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(containerjTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadShowTimejMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadShowTimejMenuItemActionPerformed
        // TODO add your handling code here:
        FileSelector load = new FileSelector(this, true);
        
        
        
    }//GEN-LAST:event_loadShowTimejMenuItemActionPerformed

    private void quitjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitjMenuItemActionPerformed
        int quit = (JOptionPane.showConfirmDialog(
                rootPane, 
                "Are you sure you want to quit?", 
                "Qutting so soon?", 
                JOptionPane.YES_NO_OPTION));
        if (quit == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_quitjMenuItemActionPerformed

    private void addRegularjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRegularjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addRegularjButtonActionPerformed

    private void addSeniorjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSeniorjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addSeniorjButtonActionPerformed

    private void addChildjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChildjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addChildjButtonActionPerformed

    private void removeRegularjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRegularjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeRegularjButtonActionPerformed

    private void removeSeniorjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSeniorjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeSeniorjButtonActionPerformed

    private void removeChildjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeChildjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeChildjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieGUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FilmIDjTextField;
    private javax.swing.JMenuItem aboutjMenuItem;
    private javax.swing.JButton addChildjButton;
    private javax.swing.JButton addFilmjButton;
    private javax.swing.JLabel addPaneljLabel;
    private javax.swing.JButton addRegularjButton;
    private javax.swing.JButton addSeniorjButton;
    private javax.swing.JButton addShowTimejButton;
    private javax.swing.JPanel addTicketjPanel;
    private javax.swing.JSpinner addjSpinner;
    private javax.swing.JLabel cartjLabel;
    private javax.swing.JScrollPane cartjScrollPane;
    private javax.swing.JTextArea cartjTextArea;
    private javax.swing.JLabel changejLabel;
    private javax.swing.JTextField changejTextField;
    private javax.swing.JPanel checkOutjPanel;
    private javax.swing.JButton clearAlljButton;
    private javax.swing.JTabbedPane containerjTabbedPane;
    private javax.swing.JButton deleteFilmjButton;
    private javax.swing.JButton deleteShowTimejButton;
    private javax.swing.JLabel duejLabel;
    private javax.swing.JTextField duejTextField;
    private javax.swing.JButton editFilmjButton;
    private javax.swing.JPanel editFilmjPanel;
    private javax.swing.JButton editShowTimejButton;
    private javax.swing.JMenu editjMenu;
    private javax.swing.JMenu filejMenu;
    private javax.swing.JLabel filmIDjLabel;
    private javax.swing.JList<String> filmjList;
    private javax.swing.JPanel filmjPanel;
    private javax.swing.JScrollPane filmjScrollPane;
    private javax.swing.JPopupMenu.Separator filmjSeparator;
    private javax.swing.JButton firstTransjButton;
    private javax.swing.JMenu helpjMenu;
    private javax.swing.JSpinner hourjSpinner;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JButton lastTransjButton;
    private javax.swing.JButton loadFilmjButton;
    private javax.swing.JMenuItem loadFilmjMenuItem;
    private javax.swing.JButton loadShowTimejButton;
    private javax.swing.JMenuItem loadShowTimejMenuItem;
    private javax.swing.JMenuItem loadTransactionjMenuItem;
    private javax.swing.JSpinner minutesjSpinner;
    private javax.swing.JButton nextTransjButton;
    private javax.swing.JButton payCashjButton;
    private javax.swing.JButton payCheckjButton;
    private javax.swing.JButton payCreditjButton;
    private javax.swing.JButton payRewardjButton;
    private javax.swing.JButton prevTransjButton;
    private javax.swing.JMenuItem quitjMenuItem;
    private javax.swing.JLabel ratingjLabel;
    private javax.swing.JSpinner ratingjSpinner;
    private javax.swing.JButton removeChildjButton;
    private javax.swing.JLabel removePaneljLabel;
    private javax.swing.JButton removeRegularjButton;
    private javax.swing.JButton removeSeniorjButton;
    private javax.swing.JPanel removeTicketjPanel;
    private javax.swing.JSpinner removejSpinner;
    private javax.swing.JLabel runTimejLabel;
    private javax.swing.JSpinner runTimejSpinner;
    private javax.swing.JButton saveFilmjButton;
    private javax.swing.JMenuItem saveFilmjMenuItem;
    private javax.swing.JButton saveShowTimejButton;
    private javax.swing.JMenuItem saveShowTimejMenuItem;
    private javax.swing.JMenuItem saveTransactionjMenuItem;
    private javax.swing.JPanel showEditjPanel;
    private javax.swing.JTextField showFilmIDjTextField;
    private javax.swing.JLabel showIDjLabel;
    private javax.swing.JList<String> showTimejList;
    private javax.swing.JPanel showTimejPanel;
    private javax.swing.JScrollPane showTimejScrollPane;
    private javax.swing.JPopupMenu.Separator showTimejSeparator;
    private javax.swing.JComboBox<String> showTitlejComboBox;
    private javax.swing.JLabel showTitlejLabel;
    private javax.swing.JLabel tenderedjLabel;
    private javax.swing.JTextField tenderedjTextField;
    private javax.swing.JLabel ticketShowTimejLabel;
    private javax.swing.JList<String> ticketShowTimejList;
    private javax.swing.JScrollPane ticketShowTimejScrollPane;
    private javax.swing.JPanel ticketjPanel;
    private javax.swing.JLabel ticketsjLabel;
    private javax.swing.JSpinner ticketsjSpinner;
    private javax.swing.JLabel timejLabel;
    private javax.swing.JLabel titlejLabel;
    private javax.swing.JTextField titlejTextField;
    private javax.swing.JTextArea transOutputjTextArea;
    private javax.swing.JLabel transTextjLabel;
    private javax.swing.JPopupMenu.Separator transactionjSeparator;
    private javax.swing.JPanel transjPanel;
    private javax.swing.JScrollPane transjScrollPane;
    private javax.swing.JTextField transjTextField;
    // End of variables declaration//GEN-END:variables
}
